service: rs-test-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  region: eu-west-2
  profile: serverless
package:
  artifact: target/tasks-api-dev.jar

functions:
  get-tasks-api:
    handler: com.sciamanna.GetTasksHandler
    events:
      - http:
          path: /users/{userId}/tasks
          method: get